export const LOGIN_SEND_REQUEST = "LOGIN_SEND_REQUEST";
export const LOGIN_SEND_REQUEST_SUCCESS = "LOGIN_SEND_REQUEST_SUCCESS";
export const LOGIN_SEND_REQUEST_FAILED = "LOGIN_SEND_REQUEST_FAILED";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAILED = "REFRESH_TOKEN_FAILED";

export const LOG_OUT = "LOG_OUT";